version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/data/postgres:/var/lib/postgresql/data
  
  web:
    build: 
      context: web/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ${PWD}/data/firebase/configs.js:/app/js/configs.js
  