version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/data/postgres:/var/lib/postgresql/data
  
  wallet:
    build: 
      context: wallet/
      dockerfile: Dockerfile
    environment:
      port:   8080
      dbhost: postgres
      dbport: 5432
      dbuser: ${POSTGRES_USER}
      dbpass: ${POSTGRES_PASSWORD}
      dbname: ${POSTGRES_DB}
    volumes:
      - ${PWD}/wallet:/app
    ports:
      - 8086:8080
  
  web:
    build: 
      context: web/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ${PWD}/data/firebase/configs.js:/app/js/configs.js
  